language: python
env:
    - TOXENV=python
python:
    # in order of most-valuable tests first
    - "2.7"

matrix:
    # notify a failed build as soon as anything fails
    fast_finish: true

before_install:
    # the travis default umask is 002, but ubuntu's is 022
    - umask 022
    - export TOP=$PWD
install:
    - pip install --upgrade pip
    - pip install -r requirements.d/travis.txt
script: tox
after_success: coveralls
 
# sudo:false gives us the new, faster cluster and enables caches for public repos
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
cache:
    directories:
        - $HOME/.pip
        - $HOME/.pre-commit
        - $HOME/.cache
